[refactor/#107][feat/#109]
Monday-Rocket/ac_project_app pull request #110
Opened 2023-01-30 09:34 UTC by buelmanager

## 🙋 작업 목적(이슈 내용)

- #107 
- #109 

## 🔧 주요 작업 내용

  - 홈화면 두번째 탭에 자신의 직업군이 나오도록 수정 
  - 폴더 이름 수정
  - 

## 🙏 To Reviewers

- 폴더이름 변경 시, db쪽 조회에 대한 id 값을 몰라서 seq를 사용하는것 같아 seq를 조회후 변경하도록 하였어요.
  seq의 개념으로 서버에 등록되는 id값으로 통일된 값을 적용하는것도 좋을것도 같네요.

- 구조를 조금 변경한 부분이 있는데, 비효율적인 부분이 있으면 이야기 주세요 :)

2023-02-01 11:28 UTC, boring-km commented
107번이랑 109번 따로 PR 올리는게 나아보여요. 109번은 홈화면 쪽 영향 없기도 하고..

2023-02-06 04:19 UTC, buelmanager commented
@boring-km 
전체 직업군 첫번째 탭에 오고, 리스트 보이도록 추가하였습니다.

2023-02-07 11:45 UTC, boring-km approved these changes
코드 수정 잘 봤습니다. #114에서 수정 결과 이어서 볼께요 :)
@buelmanager 히스토리 확인을 위해서 merge는 squash merge가 아닌 기본 merge로 진행해주세요.

2023-02-07 11:57 UTC, boring-km requested changes
다른 탭 이동했다가 홈화면으로 돌아오면 전체 탭이 중복되는 현상 발견

![image](https://user-images.githubusercontent.com/34850203/217238552-701993b8-4e17-43c6-974e-8f441801e192.png)

2023-02-07 12:08 UTC, boring-km approved these changes
여기서 수정해서 정상 확인했습니다~

2023-02-07 12:09 UTC, merged