Fix/#98
Monday-Rocket/ac_project_app pull request #99
Opened 2023-01-12 13:31 UTC by buelmanager

## 🙋 작업 목적(이슈 내용)

-  warning_mark.svg 누락파일 추가

## 🔧 주요 작업 내용

-

## 🙏 To Reviewers

-

2023-01-12 13:52 UTC, boring-km reviewed
warningMsgTitle과 warningMsgContent가 보이는 텍스트도 Figma 디자인에 맞춰주세요 ㅎㅎ

2023-01-13 00:30 UTC, buelmanager commented
디자인 수정하였습니다  :)

2023-01-13 01:00 UTC, buelmanager commented
내용 수정감사합니다 :)

2023-01-13 13:30 UTC, boring-km requested changes
@buelmanager GoogleService-Info.plist는 빼고 force push 해주세요 ㅠㅠ

2023-01-13 14:00 UTC, boring-km approved these changes
확인 완료했습니다~

2023-01-13 14:00 UTC, merged